### ISSUE TITLE
Per Tile Movement

### ISSUE THREAD

**Issue by wini3d** [nkholski/phaser-grid-physics#10]
Can it move sprites/entities in a per tile movement and smoothly? For example, if you move the player in any direction then stop, it should exactly stop inside a tile and not halfway or part of it.

**Comment by nkholski** [comment]
Yes. That's the core reason I made this plugin.

**Comment by wini3d** [comment]
Thanks. I was just confused with the demo as the player is inside smaller 2x2 tiles when using the keyboard, but not with mouse. I would assume this is just a setup.

**Comment by nkholski** [comment]
Yes. The sprite and tile sizes can be bigger than the grid size.
