### ISSUE TITLE
Flickering and seams on latest version

### ISSUE THREAD

**Issue by wini3d** [nkholski/phaser-grid-physics#11]
Comparing the published example here and the latest, I see grid flickering and seams on the latest build.

btw, what is the commit version on this [example](http://metroid.niklasberg.se/gridPhysics/)? I would like to check it out.

![download](https://user-images.githubusercontent.com/12629729/64393544-84930980-d084-11e9-916f-5d793df2738a.jpg)

**Comment by nkholski** [comment]
Sorry, I don't remember the commit version I would guess that the seems is not caused by the plugin but by how Phaser 3 draw tiles, and that the reason is that webgl might not cut the tilesheet in exact pixels. Try canvas.

**Comment by wini3d** [comment]
Yes, I figured it's your phaser2 branch and just tested it locally. It would be nice to have the demo already in build/dist just to quick test it out locally.

I got the same effect when I use `type: Phaser.CANVAS`

**Comment by nkholski** [comment]
I still it's related to tearing, search for "tile extruder" in the phaser forums and you should find a script that can fix tilesheets.

**Comment by wini3d** [comment]
Thanks, found the link but haven't tried it yet..  

https://phaser.io/news/2018/05/webgl-tile-extruder
https://github.com/sporadic-labs/tile-extruder

just curious as why they have not added this fix?
