### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by sirzento** [nkholski/phaser-grid-physics#7]
Your example does't load. (The Example in your master branch, your hosted example website works fine)

Microsoft Edge 41.16299.15.0

**Comment by nkholski** [comment]
Made a fresh clone from git and it runs without issues here. I need error messages and more information to address the issue.

**Comment by sirzento** [comment]
I get no error message. The browser console is empty and on the Website only the link is visible. I tried open it with edge/Chrome and localhost via xampp.

**Comment by nkholski** [comment]
You need to transpire it through node. Run "npm i" in the folder then "npm run dev". I seem to forgot instructions in the README, but it's standard procedure.
