### ISSUE TITLE
Timeline for upcoming features

### ISSUE THREAD

**Issue by blachawk** [nkholski/phaser-grid-physics#9]
Where can we view a road map or timeline for enhancements that are promised on the landing page of this plugin?  This way dates are associated to when they are released?

Many thanks

**Comment by nkholski** [comment]
There are no estimates on when new features or fixes will be released. Right now I'm not working on the plugin at all but hope to return to it. Is there any enhancements, in particular, you're interested in? Are you using the plugin?
